name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set Up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'

      - name: Lint
        run: |
          npm run lint
          
      - name: Build
        run: |
          npm install
          npm run build
          - name: Netlify Deploy
          
